GET http://localhost:3001/tasks/1 HTTP/1.1

###

GET http://localhost:3001/users/1 HTTP/1.1

###

POST http://localhost:3001/users/ HTTP/1.1
content-type: application/json

{
    "name": "test user",
    "mail": "test@gmail.com"
}